import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Providers from './Providers';

const RobotoFont = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: "Rick & Morty cards",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${RobotoFont.className}`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
