import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";

const RobotoFont = Roboto({
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Rick & Morty cards",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${RobotoFont.className}`}>
        {children}
      </body>
    </html>
  );
}
